name: "Send E-Mail"

on:
    workflow_dispatch:
jobs:
       send_email:
        runs-on: ubuntu-latest
        steps: 
              - name: "Checkout Code"
                uses: actions/checkout@v2

              - name: "Setup Python Environment"
                uses: actions/setup-python@v2
                with:
                    python-version: '3.x'

              - name: "Install Dependencies"
                run: |
                       python -m pip install --upgrade pip

              - name: "Send E-Mail by executing Python script"
                run: python script.py
                env:
                     WORKFLOW_NAME: ${{ github.workflow }}
                     GITHUB_REPOSITORY: ${{ github.repository }}
                     SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
                     SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                     RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
                     WORKFLOW_RUN_ID: ${{ github.run_id }}

