name: "Send E-Mail"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Setup Python Environment"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: "Install Dependencies"
        run: python -m pip install --upgrade pip

      - name: "Send E-Mail by executing Python script"
        run: python script.py
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_RUN_ID: ${{ github.run_id }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}   
# go in github in setting in secrets and variables -> Actions -> screts-> add enviroment and creted a secret in this created the SENDER_EMAIL(add your email id),SENDER_PASSWORD(add app password created from your google account),RECEIVER_EMAIL(receiver email id).
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
